// direct-qr-generator
// Encodes whatever text/URL the user enters directly into a QR code, entirely
// client-side (via the vendored kazuhikoarase qrcode-generator library) — no
// network request, no third-party shortening/redirect service in between.
// That means the QR code keeps working forever, independent of any service's
// uptime, unlike QR codes generated by url-shortener tools that route every
// scan through their own redirect server.

const QUIET_ZONE_MODULES = 4; // standard QR "quiet zone" border, in modules

// ---------- i18n ----------
const I18N = {
  ko: {
    pageTitle: '다이렉트 QR코드 생성기',
    appTitle: '다이렉트 QR코드 생성기',
    tagline: '중간 리다이렉트 없이, 입력한 링크를 QR코드에 그대로 담아요',
    step1_title: '링크 또는 텍스트',
    contentPlaceholder: 'https://example.com',
    directNote: '입력한 내용이 QR코드에 직접 인코딩돼요. 외부 단축 서비스를 거치지 않기 때문에, 그 서비스가 사라져도 이 QR코드는 계속 작동해요.',
    errorTooLong: '입력한 내용이 너무 길어서 QR코드로 만들 수 없어요. 더 짧게 입력하거나, 링크를 줄여서 다시 시도해보세요.',
    step2_title: '다운로드 크기',
    sizeWeb_label: '512 × 512',
    sizeWeb_sub: '웹/화면용',
    sizePrint_label: '1024 × 1024',
    sizePrint_sub: '인쇄물 권장',
    sizeCustom_label: '직접 입력',
    sizeCustom_sub: '픽셀(px) 직접 지정',
    customSizeLabel: '크기(px):',
    step3_title: '색상 및 오류 복원력',
    fgColorLabel: '전경색',
    bgColorLabel: '배경색',
    eccLabel: '오류 복원력:',
    eccHint: 'QR코드 일부가 가려지거나 손상돼도 인식되게 하는 여유분이에요. 값이 높을수록 복원력은 좋아지지만 패턴이 조금 더 촘촘해져요.',
    step4_title: '미리보기 및 다운로드',
    emptyHint: '위에 링크나 텍스트를 입력하면 QR코드가 여기에 나타나요.',
    downloadPngBtn: 'PNG로 다운로드',
    downloadSvgBtn: 'SVG로 다운로드',
    footer_ai: '본 서비스는 인공지능으로 제작되었습니다. 일부 기능이 정상적으로 동작하지 않을 수 있습니다.',
    footer_privacy: '본 서비스는 외부 서버 없이 사용자의 클라이언트에서 동작하도록 설계되었으며, 개인정보 및 쿠키를 활용하지 않습니다.',
    footer_contactLabel: '피드백/기타 문의:',
  },
  en: {
    pageTitle: 'Direct QR Code Generator',
    appTitle: 'Direct QR Code Generator',
    tagline: 'No middleman redirect — your link is encoded directly into the QR code',
    step1_title: 'Link or Text',
    contentPlaceholder: 'https://example.com',
    directNote: "What you type is encoded directly into the QR code. Since it doesn't go through any third-party shortening service, this QR code keeps working even if that service disappears.",
    errorTooLong: 'What you entered is too long to fit in a QR code. Try shortening it, or use a shorter link.',
    step2_title: 'Download Size',
    sizeWeb_label: '512 × 512',
    sizeWeb_sub: 'Web / screen',
    sizePrint_label: '1024 × 1024',
    sizePrint_sub: 'Recommended for print',
    sizeCustom_label: 'Custom',
    sizeCustom_sub: 'Enter exact pixel size',
    customSizeLabel: 'Size (px):',
    step3_title: 'Color & Error Correction',
    fgColorLabel: 'Foreground',
    bgColorLabel: 'Background',
    eccLabel: 'Error correction:',
    eccHint: 'This adds redundancy so the code still scans even if part of it is covered or damaged. Higher levels recover better but make the pattern denser.',
    step4_title: 'Preview & Download',
    emptyHint: 'Enter a link or text above and the QR code will appear here.',
    downloadPngBtn: 'Download PNG',
    downloadSvgBtn: 'Download SVG',
    footer_ai: 'This service was built with AI assistance. Some features may not work exactly as expected.',
    footer_privacy: 'This service runs entirely on your device with no external server, and does not collect any personal data or use cookies.',
    footer_contactLabel: 'Feedback / inquiries:',
  },
};

const state = {
  lang: localStorage.getItem('qr-gen-lang') || 'ko',
  content: '',
  ecc: 'M',
  fg: '#000000',
  bg: '#ffffff',
  qr: null, // qrcode-generator instance, or null if empty/invalid
  moduleCount: 0,
};

function t(key) {
  return I18N[state.lang][key];
}

// ---------- DOM refs ----------
const langSwitch = document.getElementById('langSwitch');
const contentInput = document.getElementById('contentInput');
const errorHint = document.getElementById('errorHint');
const sizeGroup = document.getElementById('sizeGroup');
const customSizeRow = document.getElementById('customSizeRow');
const customSizeInput = document.getElementById('customSize');
const fgColorInput = document.getElementById('fgColor');
const bgColorInput = document.getElementById('bgColor');
const eccGroup = document.getElementById('eccGroup');
const qrCanvas = document.getElementById('qrCanvas');
const emptyHint = document.getElementById('emptyHint');
const downloadPngBtn = document.getElementById('downloadPngBtn');
const downloadSvgBtn = document.getElementById('downloadSvgBtn');
const contactEmailLink = document.getElementById('contactEmailLink');

// ---------- i18n apply ----------
function applyStaticI18n() {
  document.documentElement.lang = state.lang;
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const val = t(el.getAttribute('data-i18n'));
    if (typeof val === 'string') el.textContent = val;
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    const val = t(el.getAttribute('data-i18n-placeholder'));
    if (typeof val === 'string') el.placeholder = val;
  });
  langSwitch.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.lang === state.lang);
  });
}

function setLanguage(lang) {
  if (lang !== 'ko' && lang !== 'en') return;
  state.lang = lang;
  localStorage.setItem('qr-gen-lang', lang);
  applyStaticI18n();
  // re-run validation message (if any) in the new language
  buildQR();
  renderCanvas();
}

langSwitch.addEventListener('click', (e) => {
  const btn = e.target.closest('.lang-btn');
  if (btn) setLanguage(btn.dataset.lang);
});

// ---------- contact email (kept out of the static HTML/JS source text so basic
// scrapers scanning for an "x@y.z" pattern don't find a plain mailto address to
// harvest; it's still a real, clickable link for visitors) ----------
const CONTACT_USER = 'info';
const CONTACT_DOMAIN = ['a', 'ndyk', 'im'].join('.');
function renderContactEmail() {
  const email = `${CONTACT_USER}@${CONTACT_DOMAIN}`;
  contactEmailLink.textContent = email;
  contactEmailLink.href = `mailto:${email}`;
}

// ---------- size controls ----------
function currentPreset() {
  const checked = sizeGroup.querySelector('input[name="size"]:checked');
  return checked ? checked.value : '1024';
}

function currentSize() {
  const preset = currentPreset();
  if (preset === 'custom') {
    return Math.max(128, Math.min(2048, parseInt(customSizeInput.value, 10) || 1024));
  }
  return parseInt(preset, 10);
}

sizeGroup.addEventListener('change', () => {
  customSizeRow.style.display = currentPreset() === 'custom' ? 'flex' : 'none';
  renderCanvas();
});
customSizeInput.addEventListener('input', renderCanvas);

// ---------- color controls ----------
fgColorInput.addEventListener('input', () => {
  state.fg = fgColorInput.value;
  renderCanvas();
});
bgColorInput.addEventListener('input', () => {
  state.bg = bgColorInput.value;
  renderCanvas();
});

// ---------- error-correction controls ----------
function setEcc(level) {
  state.ecc = level;
  eccGroup.querySelectorAll('.ecc-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.ecc === level);
  });
  buildQR();
  renderCanvas();
}

eccGroup.addEventListener('click', (e) => {
  const btn = e.target.closest('.ecc-btn');
  if (btn) setEcc(btn.dataset.ecc);
});

// ---------- content input (debounced) ----------
let debounceTimer = null;
contentInput.addEventListener('input', () => {
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => {
    state.content = contentInput.value.trim();
    buildQR();
    renderCanvas();
  }, 150);
});

// ---------- QR build + render ----------
function buildQR() {
  errorHint.textContent = '';
  if (!state.content) {
    state.qr = null;
    state.moduleCount = 0;
    return;
  }
  try {
    // typeNumber 0 = let the library auto-pick the smallest QR version that fits
    const qr = qrcode(0, state.ecc);
    qr.addData(state.content);
    qr.make();
    state.qr = qr;
    state.moduleCount = qr.getModuleCount();
  } catch (err) {
    state.qr = null;
    state.moduleCount = 0;
    errorHint.textContent = t('errorTooLong');
  }
}

function renderCanvas() {
  if (!state.qr) {
    qrCanvas.classList.remove('visible');
    emptyHint.classList.remove('hidden');
    downloadPngBtn.disabled = true;
    downloadSvgBtn.disabled = true;
    return;
  }

  const totalModules = state.moduleCount + QUIET_ZONE_MODULES * 2;
  // snap to an integer cell size first so every module is a crisp, gap-free
  // square — a fractional cell size causes hairline seams between modules
  const cell = Math.max(1, Math.floor(currentSize() / totalModules));
  const actualSize = cell * totalModules;

  qrCanvas.width = actualSize;
  qrCanvas.height = actualSize;
  const ctx = qrCanvas.getContext('2d');
  ctx.fillStyle = state.bg;
  ctx.fillRect(0, 0, actualSize, actualSize);
  ctx.fillStyle = state.fg;
  for (let r = 0; r < state.moduleCount; r++) {
    for (let c = 0; c < state.moduleCount; c++) {
      if (state.qr.isDark(r, c)) {
        ctx.fillRect((c + QUIET_ZONE_MODULES) * cell, (r + QUIET_ZONE_MODULES) * cell, cell, cell);
      }
    }
  }

  qrCanvas.classList.add('visible');
  emptyHint.classList.add('hidden');
  downloadPngBtn.disabled = false;
  downloadSvgBtn.disabled = false;
}

function buildSvgString() {
  const totalModules = state.moduleCount + QUIET_ZONE_MODULES * 2;
  let rects = '';
  for (let r = 0; r < state.moduleCount; r++) {
    for (let c = 0; c < state.moduleCount; c++) {
      if (state.qr.isDark(r, c)) {
        rects += `<rect x="${c + QUIET_ZONE_MODULES}" y="${r + QUIET_ZONE_MODULES}" width="1" height="1"/>`;
      }
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${totalModules} ${totalModules}" shape-rendering="crispEdges">` +
    `<rect width="${totalModules}" height="${totalModules}" fill="${state.bg}"/>` +
    `<g fill="${state.fg}">${rects}</g></svg>`;
}

// ---------- download ----------
function timestamp() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${pad(d.getDate())}${pad(d.getMonth() + 1)}${String(d.getFullYear()).slice(-2)}_${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

downloadPngBtn.addEventListener('click', () => {
  if (!state.qr) return;
  qrCanvas.toBlob((blob) => downloadBlob(blob, `AK_QRCode_${timestamp()}.png`), 'image/png');
});

downloadSvgBtn.addEventListener('click', () => {
  if (!state.qr) return;
  const blob = new Blob([buildSvgString()], { type: 'image/svg+xml' });
  downloadBlob(blob, `AK_QRCode_${timestamp()}.svg`);
});

// ---------- init ----------
applyStaticI18n();
renderContactEmail();
setEcc(state.ecc);
renderCanvas();
